### ISSUE TITLE
HTML output in kleur

### ISSUE THREAD

**Issue by SietseVisser** [sjmulder/nostt#1]
Ik heb je programma ontdekt, en gebruik het op een site voor prive piloten: https://www.vliegen.sietse.nl
Als je op die site op 'Toon' klikt krijg je onderaan de output van je nostt programma.

Hoe mooi zou het zijn als daar HTML kleuren in gebruikt worden?
Wellicht een switch voor de command line  om aan te geven dat de output HTML moet zijn?

Sietse

**Comment by sjmulder** [comment]
Wat leuk kom m'n tooltje in gebruik te zien! Handige website ook.

Ik sta open voor zo'n functie, maar misschien kan het al met bestaande generieke tools zoals [aha](https://github.com/theZiz/aha):

    $ CLICOLOR_FORCE=1 nostt 707 | aha
    ...
    <span style="color:gray;background-color:black;">                     </span>
    <span style="color:green;background-color:black;"> NOS Teletekst</span>
    <span style="color:olive;background-color:black;"> 707 </span>
    ...

Wat je ook kunt proberen, is direct de API gebruiken:

    $ curl -s http://teletekst-data.nos.nl/json/707-1 | jq -r .content
    <span class="green ">NOS Teletekst</span>
    <span class="yellow "><a class="yellow" href="#707">707</a>
    ...

Je zou dan wat CSS moeten toevoegen voor de kleuren en je zou het webfont kunnen importeren voor de block drawing characters.

Als iets als aha of de API niet de output geeft die je hoopt, laat dan even weten wat je precies zou willen, dan kan ik kijken hoe nostt dat het beste kan ondersteunen.

**Comment by SietseVisser** [comment]
Opgelost met aha - kijk nog maar eens op https://www.vliegen.sietse.nl :)

Dank!
Sietse

**Comment by sjmulder** [comment]
Prachtig!
